export default {
  App: {},
  pageScrollEvent: {},
  socket: {},
  socketEvent: {},
  checkOrder: {
    "财务正在核对": "Finance is checking",
    "3~5分钟内未到账,请联系客服": "If the account is not available within 3 ~ 5 minutes, please contact the customer service",
    "返回首页": "Return homepage",
  },
  game: {
    "游戏中心": "Game centre",
    "提现记录": "Withdrawals record",
  },
  home: {},
  liveClassRoom: {},
  liveClassRoomNew: {},
  liveLobby: {},
  lobbyEmpty: {},
  NotFound: {},
  mine: {
    "绑定手机": "Binding mobile phone",
    "已绑定手机": "Binded mobile phone",
    "系统消息": "system information",
    "个人设置": "Personal settings",
    "点击复制": "Click to copy",
    "编辑资料": "edit information",
    "汇率": "exchange rate",
    "切换汇率": "Switching rate",
    "总资产": "Total assets",
    "充值": "Recharge",
    "提现": "withdraw",
    "额度转换": "Quota conversion",
    "更多": "More",
    "国家和地区": "National and regions",
    "王者俸禄": "King",
    "收支明细": "Income and expenditure",
    "游戏报表": "Gaming report",
    "在线商城": "online shopping mall",
    "我的装备": "My equipment",
    "我的等级": "My level",
    "加载中...": "Loading...",
    "复制成功": "Replication",
    "复制失败": "Copy failure",
  },
  login: {
    "手机号登录": "Mobile phone number login",
    "游客登录": "Tourist login",
    "登录注册代表您同意《用户注册服务协议》、《隐私政策》": "Login registration represents you agree with the <User Registration Service Agreement> and <Privacy Policy>",
    "国家/地区": "country / region",
    "请输入手机号": "Please enter phone number",
    "请输入验证码": "please enter verification code",
    "发送验证码": "Send the verification code",
    "登录": "Log in",
    "登录/注册遇到问题？": "Login/register encountered a problem?",
    "联系客服": "Contact Customer Service",
    "版本号": "version number",
    "用户协议": "User Agreement",
    "在线客服系统": "Online customer service system",
    "登录成功！": "login successful!",
    "验证码发送成功": "The verification code is successfully sent",
    "验证码发送失败": "The verification code failed",
  },
  rankList: {
    "关注": "focus on",
    "已关注": "Pay attention to",
    "钻石": "diamond",
    "收益榜": "Income list",
    "贡献榜": "Contribution list",
    "日榜": "Daily list",
    "昨日榜": "Yesterday list",
    "周榜": "Weekly list",
    "月榜": "Monthly list",
    "加载中...": "Loading...",
  },
  search: {
    "请输入您要搜索的昵称或ID": "Please enter the nickname or ID you want to search",
    "关注": "focus on",
    "已关注": "Pay attention to",
    "未搜索到相关内容": "No relevant content",
    "加载中...": "Loading...",
  },
  recharge: {
    "充值中心": "recharge centre",
    "支付渠道": "Payment channel",
    "充值金额": "Recharge amount",
    "可充值区间": "Recharge range",
    "您可以获得": "You can get",
    "钻石, 当前汇率": "Diamond, current exchange rate",
    "充值奖励": "Recharge reward",
    "最高奖励": "Maximum",
    "您将获赠": "You will get",
    "汇款姓名": "Remittance name",
    "请输入您的汇款姓名": "Please enter your remittance name",
    "汇款留言": "Remittance message",
    "选填": "Select and fill",
    "银行卡号": "Bank card number",
    "复制": "copy",
    "收款名称": "Receive name",
    "开户银行": "Bank",
    "开户网点": "Account opening point",
    "立即充值": "Immediately recharge",
    "重要提示：支付渠道将不定期进行更换，入款前请查看并确认最新账户再进行汇款。": "Important tips: The payment channel will be replaced from time to time. Please check and confirm the latest account before the payment.",
    "充值提示": "Recharge prompt",
    "为了账户安全,请绑定手机号!": "For account security, please bind the mobile phone number!",
    "绑定手机号": "Binding mobile phone number",
    "继续充值": "Continue to recharge",
    "重要提示": "important hint",
    "请进行转账后再提交订单": "Please submit the order before submitting the order",
    "未转账": "Unproof",
    "已完成转账": "Completed transfer",
    "复制成功": "Replication",
    "复制失败": "Copy failure",
  },
  service: {
    "在线客服系统": "Online customer service system",
  },
  adPopup: {
    "返回": "return",
    "关闭": "closure",
  },
  announcement: {
    "公告": "announcement",
  },
  dailyCheckIn: {
    "已连续签到": "Sign in continuously",
    "天": "sky",
    "立即签到": "Sign in now",
  },
  homeTopBar: {
    "关注": "focus on",
    "直播": "live streaming",
    "游戏": "game",
  },
  footerBar: {
    "首页": "front page",
    "充值": "Recharge",
    "宝箱": "Treasure chest",
    "游戏": "game",
    "我的": "mine",
    "任务大厅": "Mission hall",
    "去完成": "Complete",
    "已完成": "completed",
    "时间": "time",
  },
  commonPopup: {
    "更多": "More",
    "在线客服系统": "Online customer service system",
    "提现记录": "Withdrawals record",
  },
  layout: {},
  liveWidget: {},
  lobby26: {
    "开始投注": "Start betting",
    "走势图": "trend",
    "大小": "size",
    "单双": "Single and double",
    "取消": "Cancel",
    "开奖历史": "History",
    "没有更多了": "No more",
    "第": "First",
    "期": "Expect",
    "玩法说明": "Gameplay",
    "大": "Big",
    "小": "Small",
    "双": "pair",
    "单": "one",
    "中奖": "Winning award",
    "钻石": "diamond",
    "点击任意处关闭": "Click to close any place",
    "无需切换游戏大厅": "No need to switch the game hall",
  },
  lobby27: {
    "开始投注": "Start betting",
    "走势图": "trend",
    "大小": "size",
    "单双": "Single and double",
    "取消": "Cancel",
    "开奖历史": "History",
    "没有更多了": "No more",
    "第": "First",
    "期": "Expect",
    "玩法说明": "Gameplay",
    "大": "Big",
    "小": "Small",
    "双": "pair",
    "单": "one",
    "中奖": "Winning award",
    "钻石": "diamond",
    "点击任意处关闭": "Click to close any place",
    "无需切换游戏大厅": "No need to switch the game hall",
  },
  lobby28: {
    "开始投注": "Start betting",
    "取消": "Cancel",
    "开奖历史": "History",
    "没有更多了": "No more",
    "第": "First",
    "期": "Expect",
    "玩法说明": "Gameplay",
    "中奖": "Winning award",
    "钻石": "diamond",
    "点击任意处关闭": "Click to close any place",
    "无需切换游戏大厅": "No need to switch the game hall",
  },
  lobby29: {
    "开始投注": "Start betting",
    "取消": "Cancel",
    "开奖历史": "History",
    "没有更多了": "No more",
    "第": "First",
    "期": "Expect",
    "玩法说明": "Gameplay",
    "中奖": "Winning award",
    "钻石": "diamond",
    "点击任意处关闭": "Click to close any place",
    "无需切换游戏大厅": "No need to switch the game hall",
  },
  lobby30: {
    "开始投注": "Start betting",
    "走势图": "trend",
    "大小": "size",
    "红黑": "Red and black",
    "区段": "Section",
    "取消": "Cancel",
    "开奖历史": "History",
    "没有更多了": "No more",
    "第": "First",
    "期": "Expect",
    "中奖": "Winning award",
    "钻石": "diamond",
    "点击任意处关闭": "Click to close any place",
    "无需切换游戏大厅": "No need to switch the game hall",
  },
  lobby31: {
    "开始投注": "Start betting",
    "取消": "Cancel",
    "开奖历史": "History",
    "没有更多了": "No more",
    "第": "First",
    "期": "Expect",
    "玩法说明": "Gameplay",
    "中奖": "Winning award",
    "钻石": "diamond",
    "点击任意处关闭": "Click to close any place",
    "无需切换游戏大厅": "No need to switch the game hall",
  },
  lottery14: {
    "开奖历史": "History",
    "没有更多了": "No more",
    "第": "First",
    "期": "Expect",
    "玩法说明": "Gameplay",
  },
  lottery10: {
    "开奖历史": "History",
    "没有更多了": "No more",
    "第": "First",
    "期": "Expect",
    "玩法说明": "Gameplay",
  },
  lottery26: {
    "开始投注": "Start betting",
    "猜豹子": "Guessing leopard",
    "开奖历史": "History",
    "没有更多了": "No more",
    "第": "First",
    "期": "Expect",
    "玩法说明": "Gameplay",
  },
  lottery29: {
    "开始投注": "Start betting",
    "开奖历史": "History",
    "没有更多了": "No more",
    "第": "First",
    "期": "Expect",
    "玩法说明": "Gameplay",
  },
  lottery28: {
    "开始投注": "Start betting",
    "开奖历史": "History",
    "没有更多了": "No more",
    "第": "First",
    "期": "Expect",
    "玩法说明": "Gameplay",
  },
  lottery31: {
    "开始投注": "Start betting",
    "开奖历史": "History",
    "没有更多了": "No more",
    "第": "First",
    "期": "Expect",
    "玩法说明": "Gameplay",
  },
  lottery30: {
    "开始投注": "Start betting",
    "开奖历史": "History",
    "没有更多了": "No more",
    "第": "First",
    "期": "Expect",
    "玩法说明": "Gameplay",
  },
  lottery8: {
    "开奖历史": "History",
    "没有更多了": "No more",
    "第": "First",
    "期": "Expect",
    "玩法说明": "Gameplay",
  },
  navBar: {},
  lotteryBetHistory: {
    "投注记录": "betting record",
    "时间筛选": "Time screening",
    "没有更多了": "No more",
    "期号": "Issue",
    "投注内容": "Bet",
    "投注日期": "Betting date",
    "状态": "state",
    "投注": "Bet",
    "中奖": "Winning award",
    "盈利": "profit",
    "全部类型": "All types",
    "全部状态": "All states",
  },
  oldVersionBet: {
    "玩法说明": "Gameplay",
    "投注记录": "betting record",
    "开奖历史": "History",
    "本期截止：": "This period is dead:",
    "秒": "second",
    "开奖中": "In the prize",
    "充值": "Recharge",
    "返回新版": "Back to the new version",
    "投注": "Bet",
    "设置筹码": "Set up chips",
    "当前筹码": "Current chip",
    "修改筹码": "Modify the chips",
    "确认": "confirm",
    "输入自定义筹码": "Enter custom chips",
    "自定义范围1-50000": "Custom scope 1-50000",
    "返回": "return",
    "确定": "Sure",
    "确认投注": "Confirm betting",
    "第": "First",
    "期": "Expect",
    "距封盘": "Sealing",
    "删除": "delete",
    "注": "Note",
    "倍": "Doubling",
    "合": "combine",
    "钻石": "diamond",
    "余额": "Balance",
    "至少有一个投注项": "At least one bet item",
  },
  tinyWidget_anchorLevel: {},
  tinyWidget_gender: {},
  tinyWidget_userLevel: {},
  offlineHandler: {},
  attention: {
    "我的关注": "my focus",
    "热门推荐": "Popular recommendation",
    "没有更多了": "No more",
  },
  play: {
    "游戏推荐": "Gaming recommendation",
    "更多": "More",
    "没有更多了": "No more",
  },
  live: {
    "游戏推荐": "Gaming recommendation",
    "左滑更多": "Left sliding more",
    "更多": "More",
    "没有更多了": "No more",
  },
  liveMaskNew: {},
  liveOver: {
    "直播已结束": "The live broadcast has ended",
    "你的美伢": "Your beauty",
    "直播时长": "Live broadcast duration",
    "收获钻石": "Diamond",
    "观看人数": "Number of viewers",
    "返回首页": "Return homepage",
  },
  bindPhone: {
    "绑定您的手机号": "Bind your mobile phone number",
    "为了方便您存取款 请绑定手机号": "For the convenience of your payment, please bind the mobile phone number",
    "国家/地区": "country / region",
    "手机": "cell phone",
    "请输入手机号": "Please enter phone number",
    "验证码": "Verification code",
    "请输入验证码": "please enter verification code",
    "发送验证码": "Send the verification code",
    "确认": "confirm",
    "验证码发送成功": "The verification code is successfully sent",
    "验证码发送失败": "The verification code failed",
    "绑定成功！": "Successful binding!",
  },
  gameReport: {
    "今天": "today",
    "昨天": "yesterday",
    "近七天": "Nearly seven days",
  },
  editInfo: {
    "头像": "avatar",
    "昵称": "Nick name",
    "手机号": "Phone number",
    "未绑定手机": "Unbound mobile phone",
    "签名": "sign",
    "我的名片": "my card",
    "生日": "Birthday",
    "性别": "gender",
    "男": "male",
    "女": "Female",
    "我的主播印象": "My anchor impression",
    "选择年月日": "Choose the New Year",
  },
  incomeDetails: {
    "本日": "today",
    "收入": "income",
    "消费": "Consumption",
    "钻石": "diamond",
    "收入明细": "Income details",
    "消费明细": "Consumer details",
  },
  king: {
    "王者特权": "King privilege",
    "王者详情": "King details",
    "尊贵的王者V0会员，您可以享受以下权益": "The noble king V0 member, you can enjoy the following rights",
    "晋级礼金": "promotion gift",
    "不可领取": "Cannot get",
    "王者级别": "King level",
    "总充值范围": "Total recharge scope",
    "晋级彩金": "Promotion",
    "周俸禄": "Zhou Lulu",
    "王者v": "King V",
    "钻石": "diamond",
  },
  limitChange: {
    "账户余额": "Account Balance",
    "钻石": "diamond",
    "自动额度转换": "Automatic quota conversion",
    "一键回收": "One -click recycling",
    "转入": "Turn in",
    "转出": "Turn out",
    "请输入": "please enter",
    "金额": "Amount",
    "全部": "all",
    "确定": "Sure",
    "一键回收成功": "One -click recycling",
    "成功": "success",
  },
  myLevel: {
    "用户等级": "user level",
    "主播等级": "Anchor level",
  },
  myEquipment: {
    "靓号": "Liang",
    "坐骑": "Mount",
  },
  onlineStore: {
    "会员": "member",
    "靓号": "Liang",
    "坐骑": "Mount",
    "VIP会员专属特权": "VIP member exclusive privilege",
    "尊贵身份": "Noble identity",
    "携带VIP标识登场": "Carrying VIP logo debut",
    "炫酷标识": "Cool",
    "用户聊天显示VIP会员图标": "User chat display VIP member icon",
    "开通会员": "join membership",
  },
  switchExchangeRate: {},
  systemMsg: {
    "系统消息": "system information",
  },
  withdraw: {
    "提现记录": "Withdrawals record",
    "账户余额（钻石）": "Account balance (diamond)",
    "输入要提现金额": "Input to mention the current amount",
    "可提现额度": "Available amount",
    "提现还需打码量1.50打码量为彩票与游戏下注量": "The coding of withdrawal is 1.50 coding.",
    "请选择提现账户": "Please select the withdrawal account",
    "立即提现": "Immediately withdraw",
    "提现账户": "Withdrawal account",
    "添加": "Add to",
    "暂无提现账户": "No withdrawal account",
    "绑定银行卡": "Binding bank card",
    "持卡人姓名": "Cardholder's Name",
    "请输入持卡人姓名": "Please enter the name of the cardholder",
    "银行卡号": "Bank card number",
    "请输入银行卡号": "Please enter the bank card number",
    "开户地区": "Account opening",
    "请输入开户地区": "Please enter the account opening area",
    "开户银行": "Bank",
    "请输入开户银行": "Please enter the account opening bank",
    "开户网点": "Account opening point",
    "请输入开户网点": "Please enter the account opening outlet",
    "转入他人卡号将无法返回,请仔细核对卡号,避免造成不必要的损失": "If you transfer to the card number of others, you will not be able to return, please check the card number carefully to avoid unnecessary losses",
    "请选择开户银行": "Please choose the account opening bank",
    "请输入搜索关键字": "Please enter your search keywords",
    "额度说明": "Quota description",
    "充值后,游戏流水需大于您的充值金额才可提现.": "After the recharge, the game flow must be greater than your recharge amount before you can withdraw.",
  },
  userSet: {
    "语言设置": "language settings",
    "退出登录": "sign out",
  },
  anchorDetails: {
    "粉丝": "fan",
    "关注": "focus on",
    "主播印象": "Anchor impression",
    "添加印象": "Add an impression",
    "钻石贡献榜": "Diamond contribution list",
    "守护榜": "Guard list",
    "视频": "video",
    "直播": "live streaming",
    "无标题": "Untitled",
    "人看过": "Have seen",
    "已关注": "Pay attention to",
    "拉黑": "Hack",
    "加载中...": "Loading...",
  },
  withdrawalsRecord: {
    "暂无提现记录": "No withdrawal record",
  },
  graphics26: {
    "大": "Big",
    "单": "one",
  },
  graphics28: {},
  graphics29: {},
  graphics30: {},
  graphics31: {},
  ways28: {},
  ways26: {},
  ways29: {},
  ways30: {},
  ways31: {},
  POKER_bjl: {},
  POKER_lh: {},
  POKER_bjl_trans: {},
  POKER_lh_trans: {},
  POKER_zjh: {},
  result14: {},
  result10: {},
  result8: {},
  result26: {},
  chips: {
    "续投": "Drilling",
    "输入自定义筹码": "Enter custom chips",
    "自定义范围1-50000": "Custom scope 1-50000",
    "返回": "return",
    "确定": "Sure",
  },
  scrollDiv: {
    "在": "exist",
    "赢得": "win",
    "钻石": "diamond",
  },
  countryRegion: {
    "国家和地区": "National and regions",
  },
  anchorList: {},
  countryRegionCharge: {
    "更多": "More",
    "国家和地区": "National and regions",
    "加载中...": "Loading...",
  },
  myPromotion: {
    "推广收益钻石": "Promoting income diamond",
    "充入账户": "Charging an account",
    "立即提现": "Immediately withdraw",
    "您的收益明细": "Your income details",
    "邀请": "invite",
    "人": "people",
    "钻石": "diamond",
    "充值": "Recharge",
    "提现成功": "Successful withdrawal",
    "申请提现中": "Application for withdrawal",
    "复制推广链接": "Copy the promotion link",
    "复制成功": "Replication",
    "复制失败": "Copy failure",
  },
  liveMask: {
    "关注": "focus on",
    "钻石": "diamond",
    "守护": "guard",
    "人": "people",
    "实时榜单": "Real -time list",
    "进入直播间": "Enter the live broadcast room",
    "系统": "system",
    "在": "exist",
    "中,下注了": "Middle, bet",
    "跟投": "Follow up",
    "中奖": "Winning award",
    " 中,下注了 ": "Middle, bet",
    "秒": "second",
    "开奖中": "In the prize",
    "撩TA一下...": "Ta ...",
    "的名片": "Business card",
    "备注用户昵称快速通过": "Remarks users' nicknames quickly pass",
    "获取": "Obtain",
    "获取名片进度": "Get the progress of famous articles",
    "赠送礼物达到要求即可获取": "Gift gifts can be obtained",
    "1.添加时请备注昵称避免主播无法区分": "1. When adding, please note that nicknames are avoided to avoid the anchor cannot be distinguished",
    "2.联系方式如有虚假可通过客户投诉": "2. Contact information if there is false information",
    "举报": "report",
    "好像在火星": "It seems to be in Mars",
    "粉丝": "fan",
    "送出钻石": "Diamond",
    "收入钻石": "Income diamond",
    "已关注": "Pay attention to",
    "主页": "Homepage",
    "请选择举报理由": "Please select the reason for reporting",
    "更多详细信息请在说明框中描述（选填）": "For more details, please describe in the description box (select and fill)",
    "请输入举报内容": "Please enter the report content",
    "提交": "submit",
    "快去为你喜欢的主播开通守护吧": "Go to open a guardian for your favorite anchor",
    "开通守护": "Open a guardian",
    "日榜": "Daily list",
    "最后更新:": "latest update:",
    "送礼": "Give a gift",
    "任务大厅": "Mission hall",
    "去完成": "Complete",
    "已完成": "completed",
    "时间": "time",
    "奖金池剩余奖金": "Bonus pool remaining bonus",
    "中奖记录": "Winning record",
    "奖励规则": "Reward rules",
    "点击抽奖": "Click on the lottery",
    "奖池规则": "Prize pool rules",
    "大奖记录": "Prize record",
    "我的记录": "My record",
    "取消": "Cancel",
    "发送礼物": "Send a gift",
    "热门": "Popular",
    "豪": "Bold",
    "钻": "Drill",
    "赠送": "Give away",
    "直播间红包": "Live room red envelope",
    "给当前直播间观众发红包": "Send a red envelope to the current audience of the live broadcast room",
    "拼手气红包": "Fighting red envelope",
    "平均红包": "Average red envelope",
    "总金额": "lump sum",
    "请输入总金额": "Please enter the total amount",
    "数量": "quantity",
    "请输入数量": "Please enter the quantity",
    "个": "indivual",
    "恭喜发财，大吉大利": "Congratulations on getting rich, great luck",
    "延时3分钟": "Delayed 3 minutes",
    "立即发放": "Powder immediately",
    "发红包": "Red envelopes",
    "关注主播不迷路~": "Follow the anchor and not get lost ~",
    "关注并退出": "Follow and exit",
    "离开": "leave",
    "提示": "hint",
    "确认": "confirm",
    "加载中...": "Loading...",
    "请选择礼物": "Please select a gift",
  },
  editInfoPopup: {
    "保存": "keep",
    "最多输入20个字": "Enter up to 20 words",
    "本次为首次修改，修改免费": "This time is the first modification, the modification is free",
    "昵称最多8个字": "Nickname up to 8 words",
    "每次需花费0钻石（首次修改免费）": "It takes 0 diamonds each time (free of charge for the first modification)",
    "你暂时还没有收到主播印象": "You haven't received an anchor impression yet",
    "昵称": "Nick name",
    "签名": "sign",
    "我的名片": "my card",
    "主播印象": "Anchor impression",
    "加载中...": "Loading...",
  },
  myAnchorImpression: {},
  langSet: {},
  lotteryBarrage: {
    "大显身手": "Dajian",
    "点击跟注": "Click to note",
    "在": "exist",
    "中投注玩法": "Chinese betting gameplay",
    "赢得": "win",
    "钻石": "diamond",
  },
  addImpression: {
    "保存": "keep",
    "请你选择你对主播的印象": "Please choose your impression of the anchor",
    "主播印象": "Anchor impression",
    "最多选择三项": "Choose three items",
  },
  diamondRank: {
    "礼物贡献榜": "Gift contribution list",
  },
  getFansList: {
    "关注": "focus on",
    "已关注": "Pay attention to",
    "粉丝": "fan",
    "加载中...": "Loading...",
  },
  getFollowsList: {
    "关注": "focus on",
    "已关注": "Pay attention to",
    "加载中...": "Loading...",
  },
  guardRank: {
    "钻石": "diamond",
    "守护榜": "Guard list",
  },
  crzh_popup: {
    "推广收益钻石": "Promoting income diamond",
    "输入要充入的钻石数": "Enter the number of diamonds to be filled in",
    "可到账": "Can get the account",
    "充入钻石": "Charging diamond",
  },
  ljtx_popup: {
    "推广收益钻石": "Promoting income diamond",
    "输入要提取的钻石数": "Enter the number of diamonds to be extracted",
    "可到账金额": "Can get the account amount",
    "请选择提现账户": "Please select the withdrawal account",
    "立即提现": "Immediately withdraw",
  },
  liveMaskCopy: {
    "关注": "focus on",
    "钻石": "diamond",
    "守护": "guard",
    "人": "people",
    "实时榜单": "Real -time list",
    "进入直播间": "Enter the live broadcast room",
    "在": "exist",
    " 中,下注了 ": "Middle, bet",
    "秒": "second",
    "开奖中": "In the prize",
    "撩TA一下...": "Ta ...",
    "的名片": "Business card",
    "备注用户昵称快速通过": "Remarks users' nicknames quickly pass",
    "获取": "Obtain",
    "获取名片进度": "Get the progress of famous articles",
    "赠送礼物达到要求即可获取": "Gift gifts can be obtained",
    "1.添加时请备注昵称避免主播无法区分": "1. When adding, please note that nicknames are avoided to avoid the anchor cannot be distinguished",
    "2.联系方式如有虚假可通过客户投诉": "2. Contact information if there is false information",
    "举报": "report",
    "好像在火星": "It seems to be in Mars",
    "添加印象": "Add an impression",
    "粉丝": "fan",
    "送出钻石": "Diamond",
    "收入钻石": "Income diamond",
    "已关注": "Pay attention to",
    "主页": "Homepage",
    "请选择举报理由": "Please select the reason for reporting",
    "更多详细信息请在说明框中描述（选填）": "For more details, please describe in the description box (select and fill)",
    "请输入举报内容": "Please enter the report content",
    "提交": "submit",
    "快去为你喜欢的主播开通守护吧": "Go to open a guardian for your favorite anchor",
    "开通守护": "Open a guardian",
    "日榜": "Daily list",
    "最后更新:": "latest update:",
    "送礼": "Give a gift",
    "任务大厅": "Mission hall",
    "去完成": "Complete",
    "已完成": "completed",
    "时间": "time",
    "奖金池剩余奖金": "Bonus pool remaining bonus",
    "中奖记录": "Winning record",
    "奖励规则": "Reward rules",
    "奖池规则": "Prize pool rules",
    "大奖记录": "Prize record",
    "我的记录": "My record",
    "取消": "Cancel",
    "发送礼物": "Send a gift",
    "钻": "Drill",
    "赠送": "Give away",
    "直播间红包": "Live room red envelope",
    "给当前直播间观众发红包": "Send a red envelope to the current audience of the live broadcast room",
    "拼手气红包": "Fighting red envelope",
    "平均红包": "Average red envelope",
    "总金额": "lump sum",
    "请输入总金额": "Please enter the total amount",
    "数量": "quantity",
    "请输入数量": "Please enter the quantity",
    "个": "indivual",
    "恭喜发财，大吉大利": "Congratulations on getting rich, great luck",
    "发红包": "Red envelopes",
    "关注主播不迷路~": "Follow the anchor and not get lost ~",
    "关注并退出": "Follow and exit",
    "离开": "leave",
    "提示": "hint",
    "确认": "confirm",
    "加载中...": "Loading...",
    "请选择礼物": "Please select a gift",
  }
} 
